# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=20, verbose_name='商品名')),
                ('product_desc', models.CharField(max_length=50, verbose_name='商品描述')),
                ('product_prices', models.FloatField(verbose_name='商品价格')),
                ('product_cover', models.ImageField(blank=True, null=True, upload_to='goods', verbose_name='商品封面')),
                ('is_delete', models.IntegerField(choices=[(0, '否'), (1, '是')], default='0', verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 't_goods',
            },
        ),
    ]
