# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_hits',
            field=models.IntegerField(verbose_name='点击量'),
        ),
    ]
