# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_url', models.CharField(blank=True, max_length=150, verbose_name='电影图片')),
                ('movie_name', models.CharField(blank=True, max_length=20, verbose_name='电影名称')),
                ('movie_director', models.CharField(blank=True, max_length=20, verbose_name='导演')),
                ('movie_adaptor', models.CharField(blank=True, max_length=20, verbose_name='编剧')),
                ('movie_actor', models.CharField(blank=True, max_length=50, verbose_name='主演')),
                ('movie_style', models.CharField(blank=True, max_length=20, verbose_name='类型')),
                ('movie_publish', models.CharField(blank=True, max_length=30, verbose_name='上映时间')),
                ('movie_length', models.CharField(blank=True, max_length=20, verbose_name='片长')),
                ('movie_detail', models.TextField(blank=True, max_length=1000, verbose_name='剧情简介')),
                ('movie_hits', models.IntegerField(verbose_name='点击量')),
                ('is_delete', models.IntegerField(choices=[(0, '否'), (1, '是')], default='0', verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '电影列表',
                'verbose_name_plural': '电影列表',
                'db_table': 't_movies',
                'ordering': ['-movie_hits'],
            },
        ),
    ]
