# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_delete',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default='0', verbose_name='是否删除'),
        ),
    ]
